### ISSUE TITLE
Workflow gets stuck at AggregatedQuote in DAML 0.13.19

### ISSUE THREAD

**Issue by bartfaitamas** [digital-asset/ex-supply-chain#15]
I am trying to run it on the DAML 0.13.19 it works great until I run AggregatedQuote , thats where its getting stuck

**Comment by richardkapolnai-da** [comment]
Thanks for reporting this issue. It is probably because the user provided _invalid product name_ as a Buyer. Valid product names can be listed if you login as Supplier, and click on Inventory. Currently the valid names are "Product 1" and "Product 2". If I submit any other product name, I also get stuck at the same stage. We also plan to improve the Readme and maybe the error handling.

**Comment by richardkapolnai-da** [comment]
It turned out the bots hasn’t been started.
